spring.application.name=tiendaEjercicio
server.port:8090

spring.datasource.url=jdbc:mysql://localhost:3306/tiendaejerciciodb_in5bm?useSSL=false
spring.datasource.username=IN5BM
spring.datasource.password=-mondoM5a
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
